version: "3.8"
services:
  cassandra-0:
    image: cassandra:3
    restart: always
    ports:
      - 7000:7000 # gossip port
      - 9042:9042 # CQL native transport port
    volumes:
      - ./data/cassandra-node-0:/var/lib/cassandra
      - ./data/cassandra-node-0/logs:/var/log/cassandra
      - ./backup/cassandra-node-0:/backup
      - ./scripts/utils:/scripts
    environment:
      - CASSANDRA_SEEDS=cassandra-0
      - CASSANDRA_CLUSTER_NAME=cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandra-1:
    image: cassandra:3
    restart: always
    ports:
      - 1700:7000
      - 19042:9042
    volumes:
      - ./data/cassandra-node-1:/var/lib/cassandra
      - ./data/cassandra-node-1/logs:/var/log/cassandra
      - ./backup/cassandra-node-1:/backup
      - ./scripts/utils:/scripts
    environment:
      - CASSANDRA_SEEDS=cassandra-0
      - CASSANDRA_CLUSTER_NAME=cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch      
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandra-2:
    image: cassandra:3
    restart: always
    ports:
      - 27000:7000
      - 29042:9042
    volumes:
      - ./data/cassandra-node-2:/var/lib/cassandra
      - ./data/cassandra-node-2/logs:/var/log/cassandra
      - ./backup/cassandra-node-2:/backup
      - ./scripts/utils:/scripts
    environment:
      - CASSANDRA_SEEDS=cassandra-0
      - CASSANDRA_CLUSTER_NAME=cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
